### ISSUE TITLE
encountered an error while attempting to update latest block

### ISSUE THREAD

**Issue by binny1024** [hyperledger-labs/yui-ibc-solidity#134]
when i exec `NO_GEN_CODE=1 ./scripts/setup.sh testtwochainz` :
```
> Compilation skipped because --compile-none option was passed.

/Users/binny/go/src/yui-ibc-solidity/node_modules/eth-block-tracker/src/polling.js:51
        const newErr = new Error(`PollingBlockTracker - encountered an error while attempting to update latest block:\n${err.stack}`)
                       ^
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
undefined
    at PollingBlockTracker._performSync (/Users/binny/go/src/yui-ibc-solidity/node_modules/eth-block-tracker/src/polling.js:51:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by bluele** [comment]
maybe I have never encountered it...
Looks like this error is caused by truffle. If you follow [this steps](https://github.com/hyperledger-labs/yui-ibc-solidity/blob/main/.github/workflows/test.yml#L37), does it still happen frequently?

**Comment by bluele** [comment]
found the related issue: https://github.com/trufflesuite/truffle/issues/4757
It may be better to use more stable network or make sure that system resources are sufficient. ref. https://besu.hyperledger.org/en/stable/private-networks/get-started/system-requirements/#java-virtual-machine-size

**Comment by binny1024** [comment]
Thank you very much, I am not using that setup.sh right now. I deployed two besu nodes separately. This problem will not be dealt with for the time being, now I mainly want to analyze the logic related to IBC, thank you again!
