### ISSUE TITLE
Improvement of FilterLogs

### ISSUE THREAD

**Issue by yoshidan** [hyperledger-labs/yui-ibc-solidity#162]
In the current implementation, the `QueryPacketCommitments` argument, `height`, is not passed to `getAllPackets` and does not appear to be used. Therefore, depending on the timing, it is likely to get a packet later than the specified height.
I think that passing the height to `getAllPackets` and setting it in the `ToBlock` of `ethereum.FilterQuery` will prevent getting packets after the `height` and also improve performance.
The same goes for `QueryPacketAcknowledgementCommitments`.

https://github.com/hyperledger-labs/yui-ibc-solidity/blob/main/pkg/relay/ethereum/chain.go#L251
https://github.com/hyperledger-labs/yui-ibc-solidity/blob/main/pkg/relay/ethereum/events.go#L95

**Comment by bluele** [comment]
fixed at #166
