### ISSUE TITLE
limitation about design of middleware and EVM stack

### ISSUE THREAD

**Issue by dzmitry-lahoda** [hyperledger-labs/yui-ibc-solidity#223]
```
Compiler run failed:
Error: Compiler error (/solidity/libyul/backends/evm/AsmCodeGen.cpp:63):Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables. When compiling inline assembly: Variable value1 is 1 slot(s) too deep inside the stack. Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
```

I get next.

So could help if `IBCAppBase` instead of many variables, have fewer, but put into memory objects. Is it okey to do such refactoring?

Alternative have internal methods IBCAppBase for override and other public/external interface to use. So that internal better inlined.

I am super fine to run via-ir too.

What would be acceptable solution?

**Comment by bluele** [comment]
I have transferred this from yui-relayer @dzmitry-lahoda

**Comment by bluele** [comment]
I see, `onChanOpenInit` and `onChanOpenTry` have many parameters, so we get `stack too deep` error when try to call the middleware as the followings:
```
    function onChanOpenInit(
        Channel.Order order,
        string[] calldata connectionHops,
        string calldata portId,
        string calldata channelId,
        ChannelCounterparty.Data calldata counterparty,
        string calldata version
    ) external override returns (string memory) {
        return middleware.onChanOpenInit(order, connectionHops, portId, channelId, counterparty, version); // stack too deep
    }
```

I think ibc-solidity should support such a case without enabling `via-ir=true`. To mitigate the error, we should use a struct parameter instead. As you say, there is some additional gas cost, but these functions are called once and this is acceptable. I will open a PR later.

**Comment by dzmitry-lahoda** [comment]
used it in #220
