### ISSUE TITLE
Question about proof of acknowledgement

### ISSUE THREAD

**Issue by michwqy** [hyperledger-labs/yui-ibc-solidity#233]
As said in [this](https://github.com/hyperledger-labs/yui-ibc-solidity/blob/main/docs/architecture.md),
>The storage location for each commitment is calculated as follows: assume that the slot of the commitments state variable is s and a ICS-23 commitment path is p, the storage location is keccak256(keccak256(p) . s).

Path of commitment and slot are used to calculate the storage location, which is the key in state trie of Ethereum. But according to the [code](https://github.com/hyperledger-labs/yui-ibc-solidity/blob/229ef0b85e65c7ca88a37282897a27b6c17d1dac/contracts/core/04-channel/IBCPacket.sol#L150),

```typescript
function writeAcknowledgement(
		string calldata destinationPortId,
		string calldata destinationChannel,
		uint64 sequence,
		bytes calldata acknowledgement
	) external {
		...
		bytes32 ackCommitmentKey =
			IBCCommitment.packetAcknowledgementCommitmentKey(destinationPortId, destinationChannel, sequence);
		bytes32 ackCommitment = commitments[ackCommitmentKey];
		require(ackCommitment == bytes32(0), "acknowledgement for packet already exists");
		commitments[ackCommitmentKey] = keccak256(abi.encodePacked(sha256(acknowledgement)));
}		
```
The default value of the storage location is zero. 

I want to know if the relayer can claim that the value on the storage path is zero before the acknowledgement is written and obtain corresponding proof (like the key of proof is the storage location and the value is zero)? If it is possible, something wrong will happen in function ```onAcknowledgementPacket``` in ```app/20-transfer```. Because zero is not equal to```ICS20Lib.KECCAK256_SUCCESSFUL_ACKNOWLEDGEMENT_JSON```.

```typescript
	function onAcknowledgementPacket(Packet.Data calldata packet, bytes calldata acknowledgement, address)
			external
			virtual
			override
			onlyIBC
		{
			if (keccak256(acknowledgement) != ICS20Lib.KECCAK256_SUCCESSFUL_ACKNOWLEDGEMENT_JSON) {
				_refundTokens(ICS20Lib.unmarshalJSON(packet.data), packet.source_port, packet.source_channel);
			}
		}
```

**Comment by bluele** [comment]
@michwqy Thanks for your question.

According to [ICS-04](https://github.com/cosmos/ibc/tree/main/spec/core/ics-004-channel-and-packet-semantics), the commitment for acknowledgment is `hash(acknowledgement)`, which is a non-zero value. The implementation is here: https://github.com/hyperledger-labs/yui-ibc-solidity/blob/v0.3.17/contracts/core/04-channel/IBCPacket.sol#L221
Therefore, even if the relayer submits a non-existence proof of commitment, the attempt fails because the corresponding acknowledgment cannot be given.

**Comment by michwqy** [comment]
I'm not sure if I understand correctly. Assume the commit path like ```path = acks/p1/ch1/s1```
, ```commitments[path] = 0``` before the acknowledgement is written. Let the storage location is ```S```, the relayer can get the proof where key is ```S```, and value is 0. But the relayer can't construct the ```acknowledgement``` where ```sha256(acknowledgement) = 0``` (maybe  ```keccak256((sha256(acknowledgement))) = 0```). Is my understanding right?

**Comment by bluele** [comment]
@michwqy Thanks for the clarification. Yes, you are right.

**Comment by michwqy** [comment]
Thanks. I will close this issue.
