### ISSUE TITLE
`validatePortIdentifier` doesn't return false

### ISSUE THREAD

**Issue by srdtrk** [hyperledger-labs/yui-ibc-solidity#287]
Shouldn't this function return false if the loop assertion fails?

https://github.com/hyperledger-labs/yui-ibc-solidity/blob/49d88ae8151a92e086e6ca7d27a2d3651889edff/contracts/core/26-router/IBCModuleManager.sol#L116-L147

**Comment by bluele** [comment]
Thanks! We will fix it soon.
