### ISSUE TITLE
Use IBC's struct `Height` as height parameter in IClient

### ISSUE THREAD

**Issue by bluele** [hyperledger-labs/yui-ibc-solidity#50]

**Comment by siburu** [comment]
`Height` type is already here.
https://github.com/hyperledger-labs/yui-ibc-solidity/blob/main/contracts/core/types/Channel.sol#L2542

Is the intention of this issue not to `define` this type, but to `use` it everywhere?

**Comment by bluele** [comment]
Yes, more specifically, the state verification functions in IClient should receive the struct `Height`.
