### ISSUE TITLE
``createClient`` should return the clientID

### ISSUE THREAD

**Issue by lightyear15** [hyperledger-labs/yui-ibc-solidity#65]
function [``createClient``](https://github.com/hyperledger-labs/yui-ibc-solidity/blob/b1c507b339f0df551280fc78d15b6ad084c00f59/contracts/core/IBCClient.sol#L13) should return a string with the clientID just created.

**Comment by bluele** [comment]
Thanks!
Also, in order for the relayer to get a new clientID, it is better to emit an event containing it as well as ibc-go.
https://github.com/cosmos/ibc-go/blob/83315a90626edec5ec876d438c532a48c4e806be/modules/core/keeper/msg_server.go#L44

**Comment by bluele** [comment]
NOTE: we need to fix this for Connection and Channel as well

**Comment by bluele** [comment]
Currently, it has already implemented:
- https://github.com/hyperledger-labs/yui-ibc-solidity/blob/d518aaaa8c7cbb231f52efa26cc658bdf39b307c/contracts/core/25-handler/IBCClientHandler.sol#L38
- https://github.com/hyperledger-labs/yui-ibc-solidity/blob/d518aaaa8c7cbb231f52efa26cc658bdf39b307c/contracts/core/25-handler/IBCConnectionHandler.sol#L15
- https://github.com/hyperledger-labs/yui-ibc-solidity/blob/d518aaaa8c7cbb231f52efa26cc658bdf39b307c/contracts/core/25-handler/IBCChannelHandler.sol#L39
