### ISSUE TITLE
ICS-20: Use JSON for packet data serialization

### ISSUE THREAD

**Issue by bluele** [hyperledger-labs/yui-ibc-solidity#81]
This is required for compatibility with ICS and ibc-go implementation. 

ref. https://github.com/cosmos/ibc/tree/master/spec/app/ics-020-fungible-token-transfer#data-structures

**Comment by bluele** [comment]
an attempt for JSON serilalization: (WIP) https://github.com/datachainlab/yui-ibc-solidity/commits/ibc-go-beta1-compatible-ics20

**Comment by dzmitry-lahoda** [comment]
@bluele are you should you want to do that?  :)

**Comment by dzmitry-lahoda** [comment]
Ethereum chains are slower and high price.

**Comment by dzmitry-lahoda** [comment]
Packets are no JSON. They are PB afail. Right?

**Comment by dzmitry-lahoda** [comment]
Memo replaced by IBC callbacks, these are not JSON too.

Sure for demo it is great to use memo JSON. 

So question why use in main?

**Comment by dzmitry-lahoda** [comment]
ICS specs use TS to describe things because it is simple for frontend people to read.

**Comment by bluele** [comment]
@dzmitry-lahoda Thanks for your feedback.

> Cosmos is 99% Protobuf. And 1% JSON.

Yes, that is correct! The 1% indicates that packet data in each IBC app.

The encoding format of the entire packet data(including memo) is specified as json, and so is the ibc-go implementation for now.
ref. https://github.com/cosmos/ibc/tree/main/spec/app/ics-020-fungible-token-transfer#data-structures
> Note that both the FungibleTokenPacketData as well as FungibleTokenPacketAcknowledgement must be JSON-encoded (not Protobuf encoded) when they serialized into packet data.

In addition, although the memo of packet data needs to be encoded in json string, the format can be specified by the middleware. So, for example, we can use the protobuf and base64 encoding for the memo.  

If there are any issues I have missed in relation to these, please let me know:)

Also, I think the abstraction of encoding formats for packet data is also possible in our implementation. In particular, there is little reason to use inefficient json encoding between evm chain using ibc-solidity. It would be possible to use another format that is more efficient than protobuf.

**Comment by dzmitry-lahoda** [comment]
oh, thank you. how weird it is.

**Comment by dzmitry-lahoda** [comment]
yeah. abstraction would be awesome at some point. i just started with solidity) so  need to catch up.how to handle.
